#Don't edit me!
version: "3"
services:
  test_a:
      image: test-server
      build:
          context: ./server
      environment: 
      - PGDATABASE=ebikes
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGPORT=6666
      - NODE_ENV=development
      